
spring:
  web:
    resources:
      static-locations: file:./uploads/
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    url: ${DB_HOST:jdbc:mysql://localhost:3306/seat}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secretKey: ${SECRET_KEY}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

cloud:
  cloudinary:
    cloud-name: dwu92ycra
    api-key: 966841335387149
    api-secret: U6SxatcQP5_U_K_46mbQeb9LyKM

